### ISSUE TITLE
Disk Space issue

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask-tutorial-infrastructure#1]
There's a jupyterhub config that's set to 10 GB, we just need to set that.

http://zero-to-jupyterhub.readthedocs.io/en/latest/user-storage.html#size-of-storage-provisioned

**Comment by martindurant** [comment]
Did we decide what the size out to be? I think that fully running through `prep.py` generates at least 34GB, so 50GB?

**Comment by TomAugspurger** [comment]
Seems reasonable.

Note that these have to be cleaned up afterwards (manually). They're under
Compute Engine > Storage.
