### ISSUE TITLE
Use larger machine-type

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask-tutorial-infrastructure#8]
IIRC, during the tutorial we hit some issue with trying to scale to a very large number of the n1-standard-4 machines? Something with the maximum number of routes for a project?

I think it would be better to provision a smaller number of larger machines.

The preemptible pricing seems to be linear in the number of cores / RAM.

Students would still get the same amount of compute, it would just be happening on a smaller number of machines.

cc @martindurant

**Comment by martindurant** [comment]
If you think so,  I don't know.
We would need to restart the little cluster I already have running and the IP of which is now in the readme at https://github.com/martindurant/dask-tutorial-scipy-2018 .

**Comment by mrocklin** [comment]
Ideally you can keep the same cluster, but add a new node pool.

**Comment by TomAugspurger** [comment]
Yes, this is just for the preemptible node pool, which can be controlled separately.

**Comment by TomAugspurger** [comment]
This worked well.
